-- Vytvorenie tabuľky pre správy z kontaktného formulára
CREATE TABLE IF NOT EXISTS spravy (
    id INT AUTO_INCREMENT PRIMARY KEY,
    meno VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    sprava TEXT NOT NULL,
    cas TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    poznamka TEXT NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS galeria (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cesta_k_suboru VARCHAR(255) NOT NULL,
    popis VARCHAR(255) NULL,
    cas_pridania TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO users (username, password)
VALUES ('admin', '$2y$10$VW3MsX.i4NV9iibkkvUcAeDUSWNiAg8X1iakq9H2BoZirW8CxXzp.')
ON DUPLICATE KEY UPDATE username = username;
